--Alter Script
-----------

ALTER TABLE LICENCE ADD BANK_ID INT(11);

ALTER TABLE LICENCE_OPENING_STOCK_DETAILS DROP GRAMS;
ALTER TABLE LICENCE_OPENING_STOCK_DETAILS ADD GST_GRAMS DOUBLE;
ALTER TABLE LICENCE_OPENING_STOCK_DETAILS ADD NONGST_GRAMS DOUBLE;