--Select Query

SELECT ORNAMENT.ORNAMENT_ID,ORNAMENT.ORNAMENT_NAME,ORNAMENT.ORNAMENT_KEY_CODE,
--LICENCE_OPENING.LICENCE_OPENING_STOCK_DETAILS_ID,
--LICENCE_OPENING.GRAMS

CASE WHEN ENTRY.ENTRY_TYPE IS NULL THEN NULL
WHEN ENTRY.ENTRY_TYPE = 'GST' THEN LICENCE_OPENING.GRAMS
END GST_GRAMS,
CASE WHEN ENTRY.ENTRY_TYPE IS NULL THEN NULL
WHEN ENTRY.ENTRY_TYPE = 'GST' THEN LICENCE_OPENING.LICENCE_OPENING_STOCK_DETAILS_ID
END GST_OPENING_STOCK_DETAILS_ID,

CASE WHEN ENTRY.ENTRY_TYPE IS NULL THEN NULL
WHEN ENTRY.ENTRY_TYPE = 'NON_GST' THEN LICENCE_OPENING.GRAMS
END NONGST_GRAMS,
CASE WHEN ENTRY.ENTRY_TYPE IS NULL THEN NULL
WHEN ENTRY.ENTRY_TYPE = 'NON_GST' THEN LICENCE_OPENING.LICENCE_OPENING_STOCK_DETAILS_ID
END NONGST_OPENING_STOCK_DETAILS_ID

FROM ORNAMENT ORNAMENT LEFT OUTER JOIN  LICENCE_OPENING_STOCK_DETAILS LICENCE_OPENING
ON LICENCE_OPENING.ORNAMENT_ID = ORNAMENT.ORNAMENT_ID
LEFT OUTER JOIN ENTRY_TYPE ENTRY ON LICENCE_OPENING.ENTRY_TYPE_ID = ENTRY.ENTRY_TYPE_ID
WHERE 0=0
--AND (LICENCE_OPENING.ENTRY_TYPE_ID IS NULL OR ENTRY.ENTRY_TYPE='GST')
and (LICENCE_OPENING.DELETED_FLAG IS NULL OR LICENCE_OPENING.DELETED_FLAG='N')
AND (LICENCE_OPENING.LICENCE_ID IS NULL OR LICENCE_OPENING.LICENCE_ID=2)
AND ORNAMENT.DELETED_FLAG='N' AND ORNAMENT.LICENCE_ID=2
--AND (LICENCE_OPENING.ENTRY_TYPE_ID=2 OR LICENCE_OPENING.ENTRY_TYPE_ID IS NULL)
;





SELECT ORNAMENT.ORNAMENT_ID,ORNAMENT.ORNAMENT_NAME,ORNAMENT.ORNAMENT_KEY_CODE,
LICENCE_OPENING.LICENCE_OPENING_STOCK_DETAILS_ID,
LICENCE_OPENING.GST_GRAMS,LICENCE_OPENING.NONGST_GRAMS
FROM ORNAMENT ORNAMENT LEFT OUTER JOIN  	 LICENCE_OPENING
ON LICENCE_OPENING.ORNAMENT_ID = ORNAMENT.ORNAMENT_ID
WHERE 0=0
and (LICENCE_OPENING.DELETED_FLAG IS NULL OR LICENCE_OPENING.DELETED_FLAG='N')
AND (LICENCE_OPENING.LICENCE_ID IS NULL OR LICENCE_OPENING.LICENCE_ID=2)
AND ORNAMENT.DELETED_FLAG='N' AND ORNAMENT.LICENCE_ID=2
;

